#!/usr/bin/env python3
"""
run_cohort_pipeline.py  (v7)
============================
Three output folders generated after per-patient analysis:

  plots_consensus_cohort/  ← simple summary (violin + dot + donut + detection + clinical)
  merged_plots/            ← 3-panel streamline diffusion per metabolite
  cohort_comparison_wceg/  ← WCEG statistical comparison CSVs + volcano plots

No redundant plotting: per-patient plots_consensus are still generated by
generate_all_plots() as before; the NEW cohort-level folders above are
generated once after all patients complete.
"""

import multiprocessing as mp
if __name__ == "__main__":
    mp.set_start_method("spawn", force=True)

import os
import pandas as pd, sys, time, argparse, traceback
from dataclasses import dataclass, field
from typing import Dict, List, Optional

import numpy as np, pandas as pd


def _apply_metadata_patch():
    try:
        import spicem_kidney_4.core as _core
        import json as _json, os as _os, pandas as _pd

        def _patched(base_dir,condition,region_idx,
                     grid_pattern="communities_hexagonal_Region_{}.json",
                     flux_folder="exchange_fluxes"):
            region_dir=_os.path.join(base_dir,condition,f"Region_{region_idx}")
            gj=_os.path.join(region_dir,grid_pattern.format(region_idx))
            if not _os.path.exists(gj):
                gj=_os.path.join(region_dir,f"communities_Region_{region_idx}.json")
            if not _os.path.exists(gj):
                raise FileNotFoundError(f"Grid JSON missing: {region_dir}")
            with open(gj) as fh: grids=_json.load(fh)
            mc=_os.path.join(region_dir,"metadata.csv")
            if not _os.path.exists(mc):
                raise FileNotFoundError(f"Metadata CSV missing: {mc}")
            df=_pd.read_csv(mc)
            rmap={}
            for col in ["pxl_col","x","coord_x","pos_x"]:
                if col in df.columns: rmap[col]="px_x"; break
            for col in ["pxl_row","y","coord_y","pos_y"]:
                if col in df.columns: rmap[col]="px_y"; break
            for col in ["Idents","Graph.based","celltype","CellType",
                        "cell_type_annotation","annotation"]:
                if col in df.columns: rmap[col]="cell_type"; break
            df=df.rename(columns=rmap)
            for req in ["px_x","px_y","cell_type"]:
                if req not in df.columns:
                    raise KeyError(f"metadata.csv missing: {req}")
            df=df.dropna(subset=["px_x","px_y","cell_type"]).copy()
            df["cell_type"]=df["cell_type"].astype(str)
            df["px_x"]=_pd.to_numeric(df["px_x"],errors="coerce")
            df["px_y"]=_pd.to_numeric(df["px_y"],errors="coerce")
            df=df.dropna(subset=["px_x","px_y"]).copy()
            if "barcode_clean" in df.columns: df=df.set_index("barcode_clean",drop=True)
            elif "barcode" in df.columns: df=df.set_index("barcode",drop=True)
            elif df.columns[0] not in ["px_x","px_y","cell_type"]:
                df=df.set_index(df.columns[0],drop=True)
            df.index=df.index.astype(str).str.strip()
            fd=_os.path.join(region_dir,flux_folder)
            if not _os.path.isdir(fd): raise FileNotFoundError(f"Flux dir missing: {fd}")
            return grids,df,fd
        _core.load_region_data=_patched
    except ImportError:
        pass


COHORT_METADATA: List[Dict] = [
    {"id":"HK2529","age":79,"sex":"Male",  "race":"White",
     "hypertension":True, "diabetes":True, "eGFR":31.40,"fibrosis":60, "group":"DKD"},
    {"id":"HK2671","age":72,"sex":"Female","race":"White",
     "hypertension":False,"diabetes":False,"eGFR":64.08,"fibrosis":5,  "group":"Control"},
    {"id":"HK2770","age":68,"sex":"Male",  "race":"African-American",
     "hypertension":True, "diabetes":False,"eGFR":69.99,"fibrosis":15, "group":"HKD"},
    {"id":"HK2844","age":62,"sex":"Female","race":"African-American",
     "hypertension":True, "diabetes":True, "eGFR":27.81,"fibrosis":25, "group":"DKD"},
    {"id":"HK2852","age":62,"sex":"Male",  "race":"White",
     "hypertension":True, "diabetes":False,"eGFR":65.10,"fibrosis":10, "group":"Control"},
    {"id":"HK2871","age":47,"sex":"Female","race":"White",
     "hypertension":True, "diabetes":False,"eGFR":17.61,"fibrosis":60, "group":"HKD"},
    {"id":"HK2873","age":71,"sex":"Female","race":"White",
     "hypertension":True, "diabetes":True, "eGFR":47.48,"fibrosis":30, "group":"DKD"},
    {"id":"HK2874","age":74,"sex":"Male",  "race":"White",
     "hypertension":False,"diabetes":False,"eGFR":61.20,"fibrosis":0,  "group":"Control"},
    {"id":"HK2877","age":33,"sex":"Female","race":"White",
     "hypertension":True, "diabetes":True, "eGFR":16.31,"fibrosis":100,"group":"DKD"},
    {"id":"HK3035","age":62,"sex":"Male",  "race":"White",
     "hypertension":False,"diabetes":True, "eGFR":44.82,"fibrosis":15, "group":"DKD"},
    {"id":"HK3432","age":66,"sex":"Male",  "race":"White",
     "hypertension":True, "diabetes":False,"eGFR":32.03,"fibrosis":5,  "group":"HKD"},
    {"id":"HK3437","age":74,"sex":"Male",  "race":"White",
     "hypertension":True, "diabetes":True, "eGFR":31.17,"fibrosis":2,  "group":"DKD"},
    {"id":"HK3444","age":80,"sex":"Female","race":"White",
     "hypertension":True, "diabetes":False,"eGFR":37.78,"fibrosis":25, "group":"HKD"},
    {"id":"HK3513","age":90,"sex":"Male",  "race":"White",
     "hypertension":True, "diabetes":False,"eGFR":54.00,"fibrosis":2,  "group":"HKD"},
]
COHORT_META_BY_ID: Dict[str,Dict]={p["id"]:p for p in COHORT_METADATA}


@dataclass
class CohortConfig:
    data_root:    str="patient_data"
    base_out_dir: str="cohort_output"
    patients:      Optional[List[str]]=None
    regions:       List[int]=field(default_factory=lambda:[1,2,3,4,5])
    skip_existing: bool=False
    grid_pattern:  str="communities_hexagonal_Region_{}.json"
    flux_folder:   str="exchange_fluxes"
    diffusion_coefficient: float=0.1
    k_neighbors:   int=4
    grid_resolution: int=80
    gaussian_sigma: float=1.2
    permutation_iters: int=500
    min_coupling_strength: float=0.001
    top_n_plots:   int=20
    num_workers:   int=10
    random_seed:   int=42
    streamline_density: float=4.5
    streamline_lw_scale: float=2.0
    streamline_lw_base: float=0.6
    streamline_arrow_size: float=1.1
    streamline_maxlength: float=5.5
    streamline_minlength: float=0.2
    scatter_size_bg: int=14
    scatter_size_highlight: int=70
    scatter_alpha_bg: float=0.22
    scatter_alpha_highlight: float=0.82
    consensus_differential_coarsen_factor: int=2
    consensus_differential_density: float=3.2
    consensus_differential_top_n: int=10
    # Cohort-level settings
    run_cohort_consensus:   bool=True
    cohort_consensus_top_n: int=20
    clinical_fields:        List[str]=field(default_factory=lambda:["eGFR","fibrosis"])
    clinical_weight:        float=0.40
    ckd_weight:             float=0.60
    top_clinical_k:         int=5
    # Merged streamline settings
    run_merged_plots:           bool=True
    run_merged_plots_combined:  bool=True   # merged_plots_combined/
    merged_combined_p_floor:    float=0.5   # p_floor for combined score
    run_merged_plots_clinical:  bool=True   # merged_plots_clinical/ (Spearman FDR)
    clinical_padj_threshold:    float=0.20  # BH-FDR threshold (liberal for n=14)
    wceg_n_permutations:    int=1000
    wceg_alpha:             float=0.20
    merged_top_exchanges:   int=5    # max exchange rows per merged figure
    # Group comparison
    use_corrected_scores_for_comparison: bool=False
    use_wceg_comparison:                 bool=True
    spotlight_extra_mets: List[str]=field(default_factory=lambda:["hco3","gal"])
    verbose: bool=True


def _condition_label(meta): return f"Sample_{meta['group']}"
def _patient_data_dir(cfg,pid): return os.path.join(cfg.data_root,pid)
def _patient_out_dir(cfg,pid):  return os.path.join(cfg.base_out_dir,pid)
def _results_pkl_path(cfg,pid): return os.path.join(_patient_out_dir(cfg,pid),"results.pkl")

def _save_results_pkl(results,path):
    import pickle
    os.makedirs(os.path.dirname(path),exist_ok=True)
    with open(path,"wb") as f: pickle.dump(results,f,protocol=pickle.HIGHEST_PROTOCOL)

def load_patient_results(base_out_dir):
    import pickle; pr={}
    for meta in COHORT_METADATA:
        pid=meta["id"]
        path=os.path.join(base_out_dir,pid,"results.pkl")
        if not os.path.exists(path): continue
        try:
            with open(path,"rb") as f: pr[pid]=pickle.load(f)
        except Exception as e:
            print(f"  WARNING: {pid}: {e}")
    print(f"Loaded {len(pr)}/{len(COHORT_METADATA)} patients")
    return pr

def _build_analysis_config(cfg,pid):
    from spicem_kidney_4 import AnalysisConfig
    meta=COHORT_META_BY_ID[pid]
    return AnalysisConfig(
        base_dir=_patient_data_dir(cfg,pid),out_dir=_patient_out_dir(cfg,pid),
        conditions=[_condition_label(meta)],regions=cfg.regions,
        diffusion_coefficient=cfg.diffusion_coefficient,k_neighbors=cfg.k_neighbors,
        grid_resolution=cfg.grid_resolution,gaussian_sigma=cfg.gaussian_sigma,
        permutation_iters=cfg.permutation_iters,
        min_coupling_strength=cfg.min_coupling_strength,
        top_n_plots=cfg.top_n_plots,num_workers=cfg.num_workers,
        grid_pattern=cfg.grid_pattern,flux_folder=cfg.flux_folder)

def _build_plot_config(cfg):
    from plotting import PlotConfig
    return PlotConfig(
        random_seed=cfg.random_seed,
        streamline_density=cfg.streamline_density,
        streamline_lw_scale=cfg.streamline_lw_scale,
        streamline_lw_base=cfg.streamline_lw_base,
        streamline_arrow_size=cfg.streamline_arrow_size,
        streamline_maxlength=cfg.streamline_maxlength,
        streamline_minlength=cfg.streamline_minlength,
        scatter_size_bg=cfg.scatter_size_bg,
        scatter_size_highlight=cfg.scatter_size_highlight,
        scatter_alpha_bg=cfg.scatter_alpha_bg,
        scatter_alpha_highlight=cfg.scatter_alpha_highlight,
        consensus_differential_coarsen_factor=cfg.consensus_differential_coarsen_factor,
        consensus_differential_density=cfg.consensus_differential_density,
        consensus_differential_top_n=cfg.consensus_differential_top_n)


def run_single_patient(patient_id,cfg,dry_run=False):
    meta=COHORT_META_BY_ID.get(patient_id)
    if meta is None:
        return {"patient_id":patient_id,"status":"UNKNOWN_ID","error":"Not in cohort"}
    out_dir=_patient_out_dir(cfg,patient_id); cond=_condition_label(meta)
    row={"patient_id":patient_id,"group":meta["group"],
         "age":meta["age"],"sex":meta["sex"],
         "eGFR":meta["eGFR"],"fibrosis":meta["fibrosis"],
         "condition_label":cond,"status":"PENDING",
         "n_significant_mets":0,"n_plots_total":0,
         "elapsed_sec":0.0,"error":""}
    if cfg.skip_existing and os.path.exists(_results_pkl_path(cfg,patient_id)):
        row["status"]="SKIPPED"
        if cfg.verbose: print(f"  [{patient_id}] SKIP")
        return row
    if dry_run:
        cond_dir=os.path.join(_patient_data_dir(cfg,patient_id),cond)
        found=[r for r in cfg.regions
               if os.path.isdir(os.path.join(cond_dir,f"Region_{r}"))]
        row["status"]="DRY_RUN"
        if cfg.verbose: print(f"  [{patient_id}] DRY_RUN | {cond} | found={found}")
        return row
    t0=time.time()
    try:
        os.makedirs(out_dir,exist_ok=True)
        _apply_metadata_patch()
        from spicem_kidney_4 import run_analysis_pipeline,save_results_to_csv
        results=run_analysis_pipeline(_build_analysis_config(cfg,patient_id),
                                      verbose=cfg.verbose)
        row["n_significant_mets"]=len(getattr(results,"significant_mets",[]))
        save_results_to_csv(results,out_dir,verbose=cfg.verbose)
        _save_results_pkl(results,_results_pkl_path(cfg,patient_id))
        from plotting import generate_all_plots
        saved=generate_all_plots(results,cfg=_build_plot_config(cfg),
                                 verbose=cfg.verbose)
        row["n_plots_total"]=sum(len(v) for v in saved.values())
        try:
            from enhanced_plots import generate_all_enhanced_plots,generate_spotlight_report
            generate_all_enhanced_plots(results,cfg=_build_plot_config(cfg),
                                        verbose=cfg.verbose)
            generate_spotlight_report(results,cfg=_build_plot_config(cfg),
                                      extra_metabolites=cfg.spotlight_extra_mets,
                                      verbose=cfg.verbose)
        except Exception as e:
            if cfg.verbose: print(f"  [{patient_id}] WARNING enhanced: {e}")
        try:
            from plot_summarizer import create_comprehensive_summaries
            create_comprehensive_summaries(results,verbose=False)
        except Exception as e:
            if cfg.verbose: print(f"  [{patient_id}] WARNING summarizer: {e}")
        row["status"]="OK"
    except Exception as e:
        row["status"]="ERROR"; row["error"]=str(e)
        if cfg.verbose: print(f"  [{patient_id}] ERROR: {e}")
        traceback.print_exc()
    row["elapsed_sec"]=round(time.time()-t0,1)
    if cfg.verbose:
        print(f"  [{patient_id}] {row['status']}  t={row['elapsed_sec']}s  "
              f"mets={row['n_significant_mets']}")
    return row


def run_cohort(cfg=None,dry_run=False):
    if cfg is None: cfg=CohortConfig()
    patients=cfg.patients or [p["id"] for p in COHORT_METADATA]
    os.makedirs(cfg.base_out_dir,exist_ok=True)
    print("="*70)
    print("SPICEM COHORT PIPELINE  (v7)")
    print("="*70)
    print(f"Patients  : {len(patients)}")
    print(f"Outputs   :")
    print(f"  plots_consensus_cohort/   simple summary (violin+dot+donut+clinical)")
    print(f"  merged_plots/             3-panel streamline per metabolite")
    print(f"  cohort_comparison_wceg/   WCEG statistical comparison")
    if dry_run: print("MODE: DRY RUN")
    print()
    groups={}
    for pid in patients:
        g=COHORT_META_BY_ID.get(pid,{}).get("group","?")
        groups.setdefault(g,[]).append(pid)
    for g in sorted(groups): print(f"  {g:10s}: {', '.join(groups[g])}")
    print()

    rows=[]
    for i,pid in enumerate(patients,1):
        print(f"[{i}/{len(patients)}] {pid} ({COHORT_META_BY_ID[pid]['group']})")
        rows.append(run_single_patient(pid,cfg,dry_run=dry_run))
    summary_df=pd.DataFrame(rows)
    if not dry_run:
        summary_df.to_csv(os.path.join(cfg.base_out_dir,"cohort_summary.csv"),index=False)

    n_ok=int((summary_df["status"].isin(["OK","SKIPPED"])).sum())

    if n_ok>0 and not dry_run:
        pr=load_patient_results(cfg.base_out_dir)
        if not pr:
            print("  No patient results found — skipping cohort steps.")
            return summary_df

        # Build exchange records once — shared by all cohort steps
        exchange_df=None
        try:
            from consensus_exchange_network import build_exchange_records
            print("\n  Building exchange records (shared) …")
            exchange_df=build_exchange_records(pr)
            print(f"  {exchange_df['metabolite'].nunique()} metabolites")
        except Exception as e:
            print(f"  WARNING: exchange records failed: {e}")

        # ── Step 9A: Consensus summary plots ─────────────────────────────
        if cfg.run_cohort_consensus:
            print("\n"+"="*70)
            print("STEP 9A — CONSENSUS SUMMARY PLOTS (simple layout)")
            print("="*70)
            try:
                from cohort_consensus_plots import generate_cohort_consensus_plots
                cons_out=os.path.join(cfg.base_out_dir,"plots_consensus_cohort")
                saved,selected_mets,rank_df=generate_cohort_consensus_plots(
                    pr,out_dir=cons_out,
                    top_n=cfg.cohort_consensus_top_n,
                    clinical_fields=cfg.clinical_fields,
                    clinical_weight=cfg.clinical_weight,
                    ckd_weight=cfg.ckd_weight,
                    top_clinical_k=cfg.top_clinical_k,
                    verbose=cfg.verbose)
                print(f"\n  ✓ {len(saved)} consensus summary figures")
            except Exception as e:
                print(f"  ERROR: {e}"); traceback.print_exc()
                selected_mets=[]

        # ── Step 9B: Merged streamline plots (combined) ──────────────────
        if cfg.run_merged_plots_combined:
            print("\n"+"="*70)
            print("STEP 9B — MERGED STREAMLINE PLOTS (combined: CKD + clinical)")
            print("="*70)
            try:
                from merged_streamline_plots import generate_merged_streamline_plots_combined
                saved_c = generate_merged_streamline_plots_combined(
                    pr,
                    out_dir=os.path.join(cfg.base_out_dir,"merged_plots_combined"),
                    top_n=cfg.cohort_consensus_top_n,
                    clinical_fields=cfg.clinical_fields,
                    clinical_weight=cfg.clinical_weight,
                    ckd_weight=cfg.ckd_weight,
                    top_clinical_k=cfg.top_clinical_k,
                    top_exchanges=cfg.merged_top_exchanges,
                    p_floor=cfg.merged_combined_p_floor,
                    wceg_n_permutations=cfg.wceg_n_permutations,
                    wceg_alpha=cfg.wceg_alpha,
                    exchange_df=exchange_df,
                    cfg=_build_plot_config(cfg),
                    verbose=cfg.verbose)
                print(f"  ✓ {len(saved_c)} combined figures")
            except Exception as e:
                print(f"  ERROR: {e}"); traceback.print_exc()

        # ── Step 9C: WCEG group comparisons + volcano plots ───────────────
        print("\n"+"="*70)
        print("STEP 9C — WCEG GROUP COMPARISONS + VOLCANO PLOTS")
        print("="*70)
        comparison_results = {}
        try:
            from cohort_comparison import ComparisonConfig, run_full_cohort_comparison
            comp_cfg = ComparisonConfig(
                base_out_dir=cfg.base_out_dir,
                n_permutations=cfg.wceg_n_permutations,
                perm_seed=cfg.random_seed,
                p_thresh=0.05,
                verbose=cfg.verbose)
            comparison_results = run_full_cohort_comparison(
                pr, comp_cfg)
            print("  ✓ WCEG comparisons and volcano plots saved")
        except Exception as e:
            print(f"  ERROR: {e}"); traceback.print_exc()

        # ── Step 9D: Merged streamline plots for WCEG-significant mets ────
        if comparison_results:
            print("\n"+"="*70)
            print("STEP 9D — MERGED STREAMLINE PLOTS (WCEG-significant mets)")
            print("  Metabolites = significant hits from WCEG volcano")
            print("="*70)
            try:
                from merged_streamline_plots import (
                    generate_merged_streamline_plots_wceg_sig)
                saved_ws = generate_merged_streamline_plots_wceg_sig(
                    pr,
                    comparison_results=comparison_results,
                    out_dir=os.path.join(cfg.base_out_dir,"merged_plots_wceg_sig"),
                    wceg_n_permutations=cfg.wceg_n_permutations,
                    wceg_alpha=cfg.wceg_alpha,
                    exchange_df=exchange_df,
                    cfg=_build_plot_config(cfg),
                    top_metabolites=20,
                    top_exchanges=cfg.merged_top_exchanges,
                    verbose=cfg.verbose)
                total = sum(len(v) for v in saved_ws.values())
                print(f"  ✓ {total} WCEG-sig figures across {len(saved_ws)} comparisons")
            except Exception as e:
                print(f"  ERROR: {e}"); traceback.print_exc()

        # ── Step 9E: Clinical-correlation merged plots ─────────────────────
        if cfg.run_merged_plots_clinical:
            print("\n"+"="*70)
            print("STEP 9E — MERGED STREAMLINE PLOTS (clinical correlation)")
            print("  Method: Spearman rho + BH-FDR across all patients")
            print("="*70)
            try:
                from merged_streamline_plots import (
                    generate_merged_streamline_plots_clinical)
                saved_cl = generate_merged_streamline_plots_clinical(
                    pr,
                    out_dir=os.path.join(cfg.base_out_dir,
                                         "merged_plots_clinical"),
                    clinical_fields=cfg.clinical_fields,
                    padj_threshold=cfg.clinical_padj_threshold,
                    top_metabolites=cfg.cohort_consensus_top_n,
                    top_exchanges=cfg.merged_top_exchanges,
                    p_floor=cfg.merged_combined_p_floor,
                    exchange_df=exchange_df,
                    cfg=_build_plot_config(cfg),
                    verbose=cfg.verbose)
                print(f"  ✓ {len(saved_cl)} clinical-correlation figures")
            except Exception as e:
                print(f"  ERROR: {e}"); traceback.print_exc()

    print("\n"+"="*70+"  SUMMARY")
    for status,count in summary_df["status"].value_counts().items():
        print(f"  {status:15s}: {count}")
    return summary_df


def _parse_args():
    p=argparse.ArgumentParser(description="SPICEM cohort pipeline v7")
    p.add_argument("--data-root",      default="patient_data")
    p.add_argument("--out-dir",        default="cohort_output")
    p.add_argument("--patient",        nargs="+",default=None)
    p.add_argument("--regions",        nargs="+",type=int,default=[1,2,3,4,5])
    p.add_argument("--skip-existing",  action="store_true")
    p.add_argument("--dry-run",        action="store_true")
    p.add_argument("--workers",        type=int,default=10)
    p.add_argument("--perms",          type=int,default=500)
    p.add_argument("--seed",           type=int,default=42)
    p.add_argument("--top-n",          type=int,default=20)
    p.add_argument("--top-clinical-k", type=int,default=5)
    p.add_argument("--wceg-perms",     type=int,default=1000)
    p.add_argument("--wceg-alpha",     type=float,default=0.20)
    p.add_argument("--no-consensus",   action="store_true")
    p.add_argument("--no-merged",      action="store_true")
    p.add_argument("--no-merged-wceg", action="store_true",
                   help="Skip WCEG-weighted merged plots folder")
    p.add_argument("--no-merged-diff",  action="store_true",
                   help="Skip differential merged plots folder")
    p.add_argument("--no-merged-combined", action="store_true",
                   help="Skip combined merged plots folder")
    p.add_argument("--combined-p-floor",   type=float, default=0.5,
                   help="p_floor for combined score (default 0.5)")
    p.add_argument("--diff-top-mets",   type=int, default=20,
                   help="Top N significant metabolites per comparison (default 20)")
    p.add_argument("--merged-top-k",   type=int,default=5,
                   help="Max exchange rows per merged figure (default 5)")
    p.add_argument("--no-wceg",        action="store_true")
    p.add_argument("--use-corrected",  action="store_true")
    p.add_argument("--quiet",          action="store_true")
    return p.parse_args()

if __name__=="__main__":
    args=_parse_args()
    cfg=CohortConfig(
        data_root=args.data_root,base_out_dir=args.out_dir,
        patients=args.patient,regions=args.regions,
        skip_existing=args.skip_existing,num_workers=args.workers,
        permutation_iters=args.perms,random_seed=args.seed,
        run_cohort_consensus=not args.no_consensus,
        cohort_consensus_top_n=args.top_n,
        top_clinical_k=args.top_clinical_k,
        run_merged_plots=not args.no_merged,
        run_merged_plots_wceg=not args.no_merged_wceg,
        run_merged_plots_differential=not args.no_merged_diff,
        merged_diff_top_metabolites=args.diff_top_mets,
        run_merged_plots_combined=not args.no_merged_combined,
        merged_combined_p_floor=args.combined_p_floor,
        merged_top_exchanges=args.merged_top_k,
        wceg_n_permutations=args.wceg_perms,
        wceg_alpha=args.wceg_alpha,
        use_corrected_scores_for_comparison=args.use_corrected,
        use_wceg_comparison=not args.no_wceg,
        verbose=not args.quiet)
    summary=run_cohort(cfg=cfg,dry_run=args.dry_run)
    sys.exit(0 if (summary["status"]=="ERROR").sum()==0 else 1)
